package git

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

// RepoDir is the local path to the cloned git repository.
var RepoDir = "/repo"

// SetupRepo clones the GitHub repo if it doesn't exist, or pulls latest changes.
func SetupRepo() error {
	repoURL := os.Getenv("GITHUB_REPO_URL")
	if repoURL == "" {
		return fmt.Errorf("GITHUB_REPO_URL environment variable not set")
	}

	// Configure git identity
	runGit("config", "--global", "user.email", "self-healing-bot@automated.dev")
	runGit("config", "--global", "user.name", "Self-Healing Bot")

	if _, err := os.Stat(RepoDir + "/.git"); os.IsNotExist(err) {
		log.Println("📥 Cloning repository...")
		if err := runGitInDir("/", "clone", repoURL, RepoDir); err != nil {
			return fmt.Errorf("failed to clone repo: %w", err)
		}
	} else {
		log.Println("📥 Pulling latest changes...")
		if err := runGitInDir(RepoDir, "checkout", "main"); err != nil {
			// Try 'master' as fallback
			runGitInDir(RepoDir, "checkout", "master")
		}
		runGitInDir(RepoDir, "pull", "origin")
	}

	return nil
}

// CreatePR creates a new branch, commits the changes, pushes, and opens a PR.
func CreatePR(service string, fixDescription string) error {
	// Generate unique branch name with timestamp
	timestamp := time.Now().Format("20060102-150405")
	branch := fmt.Sprintf("auto-fix/%s/%s", service, timestamp)

	log.Printf("🔀 Creating branch: %s", branch)

	// Ensure we're on main/master first
	if err := runGitInDir(RepoDir, "checkout", "main"); err != nil {
		runGitInDir(RepoDir, "checkout", "master")
	}
	runGitInDir(RepoDir, "pull", "origin")

	// Create and switch to new branch
	if err := runGitInDir(RepoDir, "checkout", "-b", branch); err != nil {
		return fmt.Errorf("failed to create branch %s: %w", branch, err)
	}

	// Stage all changes
	if err := runGitInDir(RepoDir, "add", "-A"); err != nil {
		return fmt.Errorf("failed to stage changes: %w", err)
	}

	// Check if there are actual changes
	output, _ := runGitOutput(RepoDir, "status", "--porcelain")
	if strings.TrimSpace(output) == "" {
		log.Println("⚠️ No changes to commit, skipping PR")
		runGitInDir(RepoDir, "checkout", "main")
		return nil
	}

	// Commit
	commitMsg := fmt.Sprintf("🤖 auto-fix(%s): %s", service, fixDescription)
	if err := runGitInDir(RepoDir, "commit", "-m", commitMsg); err != nil {
		return fmt.Errorf("failed to commit: %w", err)
	}

	// Push
	if err := runGitInDir(RepoDir, "push", "-u", "origin", branch); err != nil {
		return fmt.Errorf("failed to push branch: %w", err)
	}

	// Create PR using gh CLI
	prTitle := fmt.Sprintf("[Auto-Fix] %s - %s", service, fixDescription)
	prBody := fmt.Sprintf("## 🤖 Automated Fix\n\n**Service:** %s\n**Issue:** %s\n**Time:** %s\n\nThis PR was automatically generated by the Self-Healing Infrastructure system using Google Jules AI agent.\n\n⚠️ Please review before merging.",
		service, fixDescription, time.Now().Format(time.RFC3339))

	if err := runGhInDir(RepoDir, "pr", "create",
		"--title", prTitle,
		"--body", prBody,
		"--base", "main",
	); err != nil {
		// Try with master as base
		if err2 := runGhInDir(RepoDir, "pr", "create",
			"--title", prTitle,
			"--body", prBody,
			"--base", "master",
		); err2 != nil {
			return fmt.Errorf("failed to create PR: %w", err)
		}
	}

	log.Printf("✅ PR created: %s", branch)
	return nil
}

func runGit(args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func runGitInDir(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func runGitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func runGhInDir(dir string, args ...string) error {
	cmd := exec.Command("gh", args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = append(os.Environ(), "GH_TOKEN="+os.Getenv("GITHUB_TOKEN"))
	return cmd.Run()
}
